### ISSUE TITLE
使用 babel-preset-env

### ISSUE THREAD

**Issue by hezhii** [brickspert/react-family#1]
在安装 `babel-preset-es2015` 时，注意到现在推荐使用 `babel-preset-env`。

`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! `

于是就了解了一下 `babel-preset-env`，它可以根据运行环境智能的转换代码，而不是一股脑的转换成 `ES5`，更能充分的发挥新版本的特性。是否考虑使用 `babel-preset-env` 替换大堆预设？

**Comment by brickspert** [comment]
@hezhii 感谢~后续我这边替换下。

**Comment by hezhii** [comment]
我是初学者，正在跟着您的那篇[教程](https://github.com/brickspert/blog/issues/1)学习~~~~

之前只研究了一下 React 官方的文档，现在跟着教程，可以对整个环境的搭建有一个基本的了解，不断地跟进其他需要掌握的知识，实在是太棒了！！

**Comment by brickspert** [comment]
@hezhii 感谢认可。感谢感谢~

**Comment by Josncb** [comment]
你试过在服务器上面运行了吗？我把这个项目打包后发现在https上面 Loading chunk 失败。

**Comment by brickspert** [comment]
@Josncb 当然运行过呀~你姿势不对
