### ISSUE TITLE
build完报：例外被抛出且未被接住

### ISSUE THREAD

**Issue by chenhongen** [brickspert/react-family#11]
RT

**Comment by brickspert** [comment]
@chenhongen 求截图

**Comment by chenhongen** [comment]
![2018-06-10_164610](https://user-images.githubusercontent.com/16499303/41199939-fce4086a-6ccd-11e8-8d74-9b0151f4754f.png)

**Comment by brickspert** [comment]
@chenhongen 你这是IE8吧。。看这里。
https://github.com/brickspert/react-family-ie8
