### ISSUE TITLE
路由报错

### ISSUE THREAD

**Issue by Johnnylee1992** [brickspert/react-family#12]
路由报错 切换到react-redux 4.x版本依然报错；大神帮忙看看
![_20180621103646](https://user-images.githubusercontent.com/34331221/41695037-d8cba512-753f-11e8-8c74-1ebda80c3d8e.png)

**Comment by brickspert** [comment]
what??啥错误

**Comment by brickspert** [comment]
我前几天没看到图片。。。真尴尬
你这个就是简单的文件不存在啊。。路径写错了，或者pages没配置。
