### ISSUE TITLE
webpack4使用extract-text-webpack-plugin就报错

### ISSUE THREAD

**Issue by cooleffort** [brickspert/react-family#14]
![image](https://user-images.githubusercontent.com/41810885/43363812-3df8b3a2-9337-11e8-8787-59826de1b8a2.png)
![image](https://user-images.githubusercontent.com/41810885/43363817-48c79bd6-9337-11e8-8c4b-d4ab9ec2a823.png)

**Comment by brickspert** [comment]
@cooleffort 善用搜索引擎
https://github.com/webpack/webpack/issues/6568#issuecomment-369499680
