### ISSUE TITLE
webpack run start错误

### ISSUE THREAD

**Issue by BlowinInWind** [brickspert/react-family#2]
![wechatimg2](https://user-images.githubusercontent.com/7484227/34716279-4d70ba98-f56a-11e7-8f41-95e908cf580f.jpeg)

**Comment by BlowinInWind** [comment]
webpack-dev-server运行项目报错

**Comment by BlowinInWind** [comment]
新下载项目npm install之后在运行就这样

**Comment by brickspert** [comment]
@jiangtong 你好，直接在根目录`npm start`呀。可以执行的哦。是不是你哪里搞错了？

`webpack_study`是什么？
