### ISSUE TITLE
热更新的时候有个 warning

### ISSUE THREAD

**Issue by Rpeanut** [brickspert/react-family#3]
`patch.dev.js:141 React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ (props) {
        return _react2.default.createElement(
            _Bundle2.default,
            { load: component },
            function (Component) {
                return Component ? _react2.de…`

**Comment by brickspert** [comment]
@Rpeanut 确实是，热更新的时候会有这个警告。 并且热更新失效了，因为`react-hot-loader`的版本不稳定，我之后会修复这个问题的。请等待。。
