### ISSUE TITLE
项目打包后的check加载失败问题

### ISSUE THREAD

**Issue by Josncb** [brickspert/react-family#5]
![1d516b2c-9765-43e1-9a75-bcdb271cbcd3](https://user-images.githubusercontent.com/25879328/37751299-9c091d54-2dcc-11e8-897a-77e33a9365ec.png)

只修改webpack 的output 的publicPath  = ‘/’ 改为 './'来放在 github上加载

**Comment by Josncb** [comment]
项目虽然在本地运行没毛病，放在线上就不行了

**Comment by brickspert** [comment]
@Josncb 我看看你的访问路径是啥？

**Comment by brickspert** [comment]
@Josncb 看看 这个 https://github.com/brickspert/blog/issues/1#issuecomment-345174957
