### ISSUE TITLE
Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the UserInfo component.

### ISSUE THREAD

**Issue by FWC1994** [brickspert/react-family#6]
页面切换的时候会出现这个警告 不太清楚这个警告是由于什么原因导致的
`Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the UserInfo component.`

**Comment by brickspert** [comment]
我用`npm install`就会有这个问题
用`cnpm install`就没这个问题。
有点尴尬，我再查查

**Comment by brickspert** [comment]
可以了，更新下代码就好了。
