### ISSUE TITLE
node 执行js 

### ISSUE THREAD

**Issue by MEEllis** [brickspert/react-family#8]
\react-family\src\redux>node build   

报错： Unexpected token import

**Comment by brickspert** [comment]
不能这么执行的哦。亲

**Comment by MEEllis** [comment]
![i 8 d2 1rg7hnst30vzf v](https://user-images.githubusercontent.com/14042373/38969176-7ecd9962-43c1-11e8-95c3-5a5ceda56bb6.png)
我是按着你这个地方的案例去实践的，node执行环境无法识别import ， 你这边在编码这里的时候，可以执行吗？ 还是说我理解你这边的文章和你表达的意思有出入呢？

**Comment by brickspert** [comment]
@MEEllis 
如果你还没解决，方便的话把源码发给邮箱，我看看。
576679268@qq.com

**Comment by brickspert** [comment]
@MEEllis 在你给我的代码基础上，我执行了`npm install`，
然后切到redux目录，执行了`webpack testRedux.js build.js`
然后执行`node build.js`
并没有发现和你一样的问题啊。你删除node_modules，按我的再试试，

**Comment by brickspert** [comment]
另外你看看你的`webpack`是不是装的v3。切成v3试试
